MetmarMVCApp/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MetmarMVCApp.Models;

namespace MetmarMVCApp.Controllers
{
    public class ItemsController : Controller
    {
        private MetmarModel db = new MetmarModel();
        private static List<Order> list = new List<Order>();
        // GET: Items
        public ActionResult Index(string categoryName , string searchString)
        {

            var CategoryLst = new List<string>();
            var CategoryQry = from d in db.Kategorie
                              orderby d.Nazwa
                              select d.Nazwa;

            CategoryLst.AddRange(CategoryQry.Distinct());
            ViewBag.categoryName = new SelectList(CategoryLst);


            var przedmioty = db.Przedmioty.Include(p => p.Kategorie);

            if (!String.IsNullOrEmpty(searchString))
            {
                przedmioty = przedmioty.Where(s => s.Nazwa.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(categoryName))
            {
                przedmioty = przedmioty.Where(x => x.Kategorie.Nazwa.Contains(categoryName));
            }

            return View(przedmioty.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            if (przedmioty == null)
            {
                return HttpNotFound();
            }
            return View(przedmioty);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            ViewBag.IdKategorii = new SelectList(db.Kategorie, "Id", "Nazwa");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nazwa,IdKategorii,Kaucja,StawkaDzien,StawkaGodzinowa,Cena,IsPrice,Wartosc,IsSki")] Przedmioty przedmioty)
        {
            if (ModelState.IsValid)
            {
                db.Przedmioty.Add(przedmioty);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdKategorii = new SelectList(db.Kategorie, "Id", "Nazwa", przedmioty.IdKategorii);
            return View(przedmioty);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            if (przedmioty == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdKategorii = new SelectList(db.Kategorie, "Id", "Nazwa", przedmioty.IdKategorii);
            return View(przedmioty);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nazwa,IdKategorii,Kaucja,StawkaDzien,StawkaGodzinowa,Cena,IsPrice,Wartosc,IsSki")] Przedmioty przedmioty)
        {
            if (ModelState.IsValid)
            {
                db.Entry(przedmioty).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdKategorii = new SelectList(db.Kategorie, "Id", "Nazwa", przedmioty.IdKategorii);
            return View(przedmioty);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            if (przedmioty == null)
            {
                return HttpNotFound();
            }
            return View(przedmioty);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            db.Przedmioty.Remove(przedmioty);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MetmarMVCApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MetmarMVCApp.Models;


namespace MetmarMVCApp.Controllers
{
    public class OrderController : Controller
    {
        private MetmarModel db = new MetmarModel();
        private static List<Order> orderList = new List<Order>();

        //public OrderController(List<Order> List)
        //{
        //    orderList = List;
        //}

        public OrderController()
        {

        }

        // GET: Order
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost, ActionName("Index")]
        public ActionResult IndexConfirm()
        {
            return RedirectToAction("ClientTable");
        }

        public ActionResult OrderTable()
        {
            return View(orderList);
        }

        public ActionResult ClientTable(string searchLastNm)
        {

            var ClientQry = from d in db.Klienci
                            select d;

            if (!String.IsNullOrEmpty(searchLastNm))
            {
                ClientQry = ClientQry.Where(c => c.Nazwisko.Contains(searchLastNm));
            }

            return View(ClientQry.ToList());
        }

        [HttpPost, ActionName("ClientTable")]
        public ActionResult ClientTableNext()
        {
            return RedirectToAction("ItemTable");
        }

        public ActionResult ItemTable(string categoryName, string searchString)
        {

            var CategoryLst = new List<string>();
            var CategoryQry = from d in db.Kategorie
                              orderby d.Nazwa
                              select d.Nazwa;

            CategoryLst.AddRange(CategoryQry.Distinct());
            ViewBag.categoryName = new SelectList(CategoryLst);


            var przedmioty = db.Przedmioty.Include(p => p.Kategorie);

            if (!String.IsNullOrEmpty(searchString))
            {
                przedmioty = przedmioty.Where(s => s.Nazwa.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(categoryName))
            {
                przedmioty = przedmioty.Where(x => x.Kategorie.Nazwa.Contains(categoryName));
            }

            return View(przedmioty.ToList());
        }

        [HttpPost, ActionName("ItemTable")]
        public ActionResult ItemTableNext()
        {
            return RedirectToAction("OrderTable");
        }

        // Get: Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order orderItem = orderList.Find(i => i.Item.Id == id);
            if (orderItem == null)
            {
                return HttpNotFound();
            }
            var Item = orderItem.Item as Przedmioty;
            return View(Item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nazwa,IdKategorii,Kaucja,StawkaDzien,StawkaGodzinowa,Cena,IsPrice,Wartosc,IsSki")] Przedmioty newItem)
        {
            if (ModelState.IsValid)
            {
                Order oldOrder = orderList.Find(i => i.Item.Id == newItem.Id);
                orderList.Remove(oldOrder);
                var newOrder = new Order
                {
                    Item = newItem,
                    Count = oldOrder.Count,
                    DateCreated = oldOrder.DateCreated
                };
                orderList.Add(newOrder);
                return RedirectToAction("OrderTable");
            }
            return View(newItem);
        }

        // Get: Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order orderItem = orderList.Find(i => i.Item.Id == id);
            if (orderItem == null)
            {
                return HttpNotFound();
            }
            return View(orderItem);
        }

        // Post: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            Order orderItem = orderList.Find(i => i.Item.Id == id);
            if (orderItem.Count > 1)
            {
                orderList.Remove(orderItem);
                orderItem.Count--;
                orderList.Add(orderItem);
            }
            else
                orderList.Remove(orderItem);

            return RedirectToAction("OrderTable");
        }

        public ActionResult AddToOrderDetails(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            if (przedmioty == null)
            {
                return HttpNotFound();
            }

            return View(przedmioty);
        }

        [HttpPost, ActionName("AddToOrderDetails")]
        [ValidateAntiForgeryToken]
        public ActionResult AddToOrderConfirm(int id, bool isDay = false)
        {
            var item = orderList.FirstOrDefault(i => i.Item.Id == id);
            Przedmioty przedmioty = db.Przedmioty.Find(id);
            if (item != null)
            {
                item.Count++;
            }
            else
            {
                var order = new Order
                {
                    Item = przedmioty,
                    Count = 1,
                    DateCreated = DateTime.Now
                };
                if (isDay == true)
                    order.ToPay = przedmioty.StawkaDzien;
                else
                {
                    order.ToPay = przedmioty.StawkaGodzinowa;
                    order.ToPay += przedmioty.Cena;
                }
                orderList.Add(order);
            }

            return RedirectToAction("ItemTable");
        }

        public ActionResult Select(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Klienci klienci = db.Klienci.Find(id);
            if (klienci == null)
            {
                return HttpNotFound();
            }
            return View(klienci);
        }

        [HttpPost, ActionName("Select")]
        [ValidateAntiForgeryToken]
        public ActionResult SelectConfirm(int id)
        {
            Klienci klienci = db.Klienci.Find(id);
            Session["Client"] = klienci;
            return RedirectToAction("ClientTable");
        }
    }
}

MetmarMVCApp/Views/Items/Create.cshtml
@model MetmarMVCApp.Models.Przedmioty

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Przedmioty</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdKategorii, "Kategoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdKategorii", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKategorii, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kaucja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kaucja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kaucja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StawkaDzien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StawkaDzien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StawkaDzien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StawkaGodzinowa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StawkaGodzinowa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StawkaGodzinowa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wartosc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wartosc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wartosc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSki, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsSki, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsSki, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MetmarMVCApp/Views/Items/Delete.cshtml
@model MetmarMVCApp.Models.Przedmioty

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Przedmioty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategorie.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategorie.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kaucja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kaucja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StawkaDzien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StawkaDzien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StawkaGodzinowa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StawkaGodzinowa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wartosc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wartosc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSki)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSki)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MetmarMVCApp/Views/Items/Details.cshtml
@model MetmarMVCApp.Models.Przedmioty

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Przedmioty</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategorie.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategorie.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kaucja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kaucja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StawkaDzien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StawkaDzien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StawkaGodzinowa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StawkaGodzinowa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wartosc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wartosc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSki)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSki)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MetmarMVCApp/Views/Items/Edit.cshtml
@model MetmarMVCApp.Models.Przedmioty

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Przedmioty</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdKategorii, "IdKategorii", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdKategorii", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKategorii, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kaucja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kaucja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kaucja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StawkaDzien, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StawkaDzien, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StawkaDzien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StawkaGodzinowa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StawkaGodzinowa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StawkaGodzinowa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wartosc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wartosc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wartosc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSki, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsSki, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsSki, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MetmarMVCApp/Views/Items/Index.cshtml
@model IEnumerable<MetmarMVCApp.Models.Przedmioty>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    @using (Html.BeginForm("Index", "Items", FormMethod.Get))
    {
    <p>
        Category: @Html.DropDownList("categoryName", "All")
        Nazwa: @Html.TextBox("SearchString")
        <input type="submit" value="Filter" />
        <div style="float:right; font-size: 24px">@Html.ActionLink("Next", "Index", "Order")</div>
    </p>
}
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Kategorie.Nazwa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nazwa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kaucja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StawkaDzien)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StawkaGodzinowa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cena)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Wartosc)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Kategorie.Nazwa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nazwa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kaucja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StawkaDzien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StawkaGodzinowa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cena)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Wartosc)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })<br />
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) <br />
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) <br />
                    @Html.ActionLink("Add", "AddToOrderDetails", new { id = item.Id })
                </td>
            </tr>
        }

    </table>